sudo: required

language: java

services:
  - docker

script:
  - mvn test -B package -DskipTests

after_success:
  - mkdir -p ~/.m2
  - sh -c 'echo "<settingsSecurity><master>$(mvn -emp place)</master></settingsSecurity>" > ~/.m2/settings-security.xml'
  - mvn -s .travis.settings.xml -B package -DdeployDocker -DskipTests
