sudo: required

language: java

services:
  - docker

script:
  - mvn test -B package -DskipTests

after_success:
  - mkdir -p ~/.m2
  - touch ~/.m2/settings-security.xml
  - mvn -s .travis.settings.xml -B package -DdeployDocker -DskipTests
