version: '3'

services:
  demogpb-customer:
    image: dcloudemo/demogpb-customer
  demogpb-catalog:
    image: dcloudemo/demogpb-catalog
  demogpb-order:
    image: dcloudemo/demogpb-order
    ports:
      - "8083:8083"

