version: '3'

#networks:
#  default:
#    external:
#      name: platform_default
      
services:
  demogpb-customer:
    image: dcloudemo/demogpb-customer:latest

  demogpb-catalog:
    image: dcloudemo/demogpb-catalog:latest

  demogpb-order:
    image: dcloudemo/demogpb-order:latest
    ports:
      - "8083:8083"
