# DOCS http://codecentric.github.io/spring-boot-admin/1.5.0/#_hystrix_ui_module
security:
  user:
    name: admin
    password: admin@123

info:
  version: 1.5.0
  description: подсистема "Администрирования и управления"

server:
  context-path:
  port: ${PORT:7070}
  ssl:
    enabled: false
  session:
    cookie:
      name: JSESSIONIDADMINSRV
  use-forward-headers: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 60
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
      management.context-path: ${server.context-path}${management.context-path}
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    homePageUrlPath: ${eureka.hostname}/

management:
  port: ${server.port}
  security.enabled: false
  context-path: /manage

turbine:
  aggregator:
    clusterConfig: ORDER,CUSTOMER,CATALOG
  appConfig: order,customer,catalog
  instanceUrlSuffix: /mgmt/hystrix.stream

spring:
  boot:
    admin:
      turbine:
        clusters: ORDER,CUSTOMER,CATALOG
        enabled: true
      context-path: /admin
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

#      turbine:
#        clusters: default
#        url: http://localhost:8989/turbine.stream
#        client.prefer-ip: true
